//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo
    {
        public int file_id { get; set; }
        public string file_name { get; set; }
        public string file_ext { get; set; }
        public byte[] file { get; set; }
        public string file_coment { get; set; }
        public Nullable<int> inc_id { get; set; }
    
        public virtual incidencia incidencia { get; set; }
    }
}
