//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class incidencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public incidencia()
        {
            this.archivos = new HashSet<archivo>();
            this.tecnicos = new HashSet<tecnico>();
        }
    
        public int inc_id { get; set; }
        public Nullable<int> priority_id { get; set; }
        public Nullable<int> ty_id { get; set; }
        public Nullable<int> maq_id { get; set; }
        public Nullable<System.DateTime> s_date { get; set; }
        public Nullable<System.DateTime> f_date { get; set; }
        public Nullable<int> s_user { get; set; }
        public Nullable<int> f_user { get; set; }
        public string coment { get; set; }
        public Nullable<int> estado_id { get; set; }
        public Nullable<System.DateTime> p_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<archivo> archivos { get; set; }
        public virtual estado estado { get; set; }
        public virtual inc_type inc_type { get; set; }
        public virtual maquina maquina { get; set; }
        public virtual priority priority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tecnico> tecnicos { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
