//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_001.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<roll> rolls { get; set; }
        public virtual DbSet<estado> estadoes { get; set; }
        public virtual DbSet<inc_type> inc_type { get; set; }
        public virtual DbSet<maquina> maquinas { get; set; }
        public virtual DbSet<priority> priorities { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<archivo> archivos { get; set; }
        public virtual DbSet<incidencia_list> incidencia_list { get; set; }
        public virtual DbSet<totalTime> totalTime { get; set; }
        public virtual DbSet<esperatime> esperatime { get; set; }
        public virtual DbSet<reparacionTime> reparacionTime { get; set; }
        public virtual DbSet<incidencia> incidencias { get; set; }
        public virtual DbSet<tecnico> tecnicos { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_list> users_list { get; set; }
    }
}
