//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_list
    {
        public int users_id { get; set; }
        public string users_name { get; set; }
        public string users_fname { get; set; }
        public string users_lname { get; set; }
        public string users_alias { get; set; }
        public string roll_name { get; set; }
        public Nullable<bool> act { get; set; }
    }
}
